### ISSUE TITLE
Docker version of compute_sparse_matrix differs from repo

### ISSUE THREAD

**Issue by rcurrie** [ucscHexmap/compute#1]
Stumbled upon this and just wanted to make a note of it:

https://github.com/ucscHexmap/compute/blob/254838415da027039d5b2102579d18ea0e115438/calc/compute_sparse_matrix.py#L182

It appears this line differs between the repo (max) and that found in the ucschexmap/compute:0.0.1 docker (min).

**Comment by mrJeppard** [comment]
Master now matches the ucschexmap/compute:0.0.2 docker image.
