### ISSUE TITLE
Cannot run docker image

### ISSUE THREAD

**Issue by Jeltje** [ucscHexmap/compute#4]
Two reasons: 
1. The command that works on my local clone:
`layout.py --layoutInputFile v5.1kgenes.tsv --colormaps colormap.tab --outputDirectory hexmap --neighborCount 6 --noLayoutAwareStats --noLayoutIndependentStats --firstAttribute disease --colorAttributeFile shared.clusters.tsv`
gives the following error:
`layout.py: error: unrecognized arguments: /usr/src/app/calc/layout.py`

The only difference between the two `layout.py` scripts is this:
```
< if __name__ == "__main__" :
<     try:
<         return_code = main(sys.argv[1:])
<     except:
<         traceback.print_exc()
<         return_code = 1
---
> if __name__ == "__main__":
>     sys.exit(main(sys.argv))
1846d1841
<     sys.exit(return_code)
```

2. When I replace the docker image `layout.py` with my working version, the program exits with this in the log:
```
Traceback (most recent call last):
  File "/usr/src/app/calc/layout.py", line 1841, in <module>
    return_code = main(sys.argv[1:])
  File "/usr/src/app/calc/layout.py", line 1837, in main
    return makeMapUIfiles(arg_obj, args)
  File "/usr/src/app/calc/layout.py", line 1378, in makeMapUIfiles
    log=None
  File "/usr/src/app/calc/compute_sparse_matrix.py", line 356, in compute_similarities
    x_corr = 1 - sklp.pairwise_distances(X=dt, Y=None, metric=metric_type, n_jobs=num_jobs)
  File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/pairwise.py", line 1247, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/pairwise.py", line 1096, in _parallel_pairwise
    for s in gen_even_slices(Y.shape[0], n_jobs))
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 28] No space left on device
```
The working directory I mount on the container is large enough; I don't see any files in the container's `/tmp`.
Where is it putting the temporary files?

**Comment by Jeltje** [comment]
More details: It goes wrong inside `compute_sparse_matrix.compute_similarities` at `#calculate pairwise similarities`, where it calls `sklp.pairwise_distances`

My container stats:
```
CONTAINER ID        NAME                 CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
6e54f3887f14        youthful_ramanujan   0.00%               1.387MiB / 240.2GiB   0.00%               648B / 0B           2.62MB / 1.14MB     1
```
I watched during the run and MEM% never goes over 1%. NET I/O also doesn't change. CPU is at 100%.

**Comment by Jeltje** [comment]
After a long hunt, I think this is the issue:
https://github.com/joblib/joblib/issues/168

I'm trying to find a workaround.

Meanwhile, the Dockerfile in master and in the releases cannot be used to create a Docker image - it looks for a hardcoded `/mnt/docker/tmp/docker-builder255470083/requirements.txt`
Maybe move this to the same directory as Dockerfile and copy from there?

**Comment by mrJeppard** [comment]
Ahhh, seems like you have had a rough saga, I apologize for that.

Several things are going on, you fixed a bug, then ran into memory limit inside your docker container, then ran into a poor design choice of needing to move a file to build the docker image. 

For the first problem (that you got around) I pushed a new docker image with the bug fix. 

For the second problem (I believe if you can fix this without re-building you should be in buisness): [try this stack post](https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

About the build:  the requirements.txt file needs to be on the same level as the Dockerfile to take advantage of their sugar for building the python environment. And we keep that file in the /build directory. I'll make a build_docker.sh script that moves that file to the root and then kicks off the docker build. But if you simply copy it there whatever build command you were using should work.

Anyway hope some of this helps and isn't too little too late. Let us know how it goes.

**Comment by Jeltje** [comment]
Not so fast...!
It wasn't a memory issue. It is a problem where the `joblib` library stores its temp files in `/dev/shm` instead of $TMPDIR. Since the temp files are rather large, this causes the disk full error.
A way around it is to set `ENV     JOBLIB_TEMP_FOLDER=/some_mounted_dir`  in the Dockerfile, but then you have to add the instruction to mount this specific directory with the `docker run` call.

It needs to be solved, otherwise you can't run this docker container at all.

**Comment by mrJeppard** [comment]
To be clear, the docker container does run on different input, and probably a subset of your input, correct ? (works with a toy example on my machine) 

You are saying that the our layout.py script, when it is calling the compute_similarities function, is over writing to a tmp dir? 

Sounds like when it is doing parallel computation, it over writes to the temp.

Probably a good next step is to try a lower number of jobs in the parallel computation.

How you would do that without changing anything is using compute_sparse_matrix.py before calling layout.py. E.g.

`python2.7 compute_sparse_matrix.py --in_file sampleXfeatures.tab --out_file sparse_sim.tab --top N --num_jobs 5`

then your `sparse_sim.tab` file is used for your --layoutInputFile going into layout.py.

if --num_jobs 1 creates the same error that your seeing I'm incorrect.

But, If I'm remembering correctly layout.py instructs compute sparse to grab a greedy number of processes. And there is some tmp dir writing that goes on.

If you'd like to email a pointer to your data I can take a direct look on Monday.

**Comment by Jeltje** [comment]
It's not your code that's the problem, directly. It's sklearn calling numpy using joblib for parallel processing. Joblib writes temporary files to /dev/shm (which is bad coding on their end). The docker container's /dev isn't large enough to handle that.

**Comment by mrJeppard** [comment]
This [s.o. post](https://stackoverflow.com/questions/44664900/oserror-errno-28-no-space-left-on-device-docker-but-i-have-space?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) suggests trying to increase the size of the tmp dir sklearn uses:
`docker run --shm-size=512m <image-name>`

Or, running with --n_jobs set to 1.
